name: CodeQL

on:
  push:
    branches: [ main ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [ 'javascript', 'java' ] # Add more languages as needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1

      - name: Build and analyze
        run: codeql analyze ${{ matrix.language }}-code

